# Generated by Django 2.2.6 on 2019-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191106_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='must_be_approved',
            field=models.BooleanField(default=False),
        ),
    ]
