# Generated by Django 2.2.6 on 2019-11-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
        ('event', '0006_auto_20191106_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(related_name='event', to='volunteer.Volunteer'),
        ),
    ]
