# Generated by Django 2.2.6 on 2019-11-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
    ]
