# Generated by Django 2.2.6 on 2019-11-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20191106_1415'),
        ('volunteer', '0004_auto_20191106_1413'),
        ('event', '0008_remove_event_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(related_name='event', to='volunteer.Volunteer'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='organisation.Organisation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media-files/event/images'),
        ),
    ]
