# Generated by Django 2.2.6 on 2019-11-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20191107_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organization',
            new_name='organisation',
        ),
    ]
