# Generated by Django 2.2.6 on 2019-11-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20191107_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='guests',
            new_name='participants',
        ),
    ]
