name: backend
channels:
  - conda-forge
dependencies:
  - python=3.7
  - psycopg2=2.8.4
  - gunicorn=19.9.0
  - pip:
      - django==2.2.7
      - djangorestframework==3.10.3
      - djangorestframework_simplejwt==4.3.0
      - django-cors-headers==3.1.1
      - coreapi==2.3.3
      - flake8==3.7.9
      - yamllint==1.18.0
      - coverage==4.5.4
      - pillow==6.2.1
