# Generated by Django 2.2.6 on 2019-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title of the call')),
                ('call_picture', models.ImageField(blank=True, null=True, upload_to='call_pictures', verbose_name='call picture')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('start_datetime', models.DateTimeField(verbose_name='start of the call')),
                ('end_datetime', models.DateTimeField(verbose_name='end of the call')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('must_be_approved', models.BooleanField(verbose_name='must be approved')),
            ],
        ),
    ]
