# Generated by Django 2.2.7 on 2019-11-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20191113_1107'),
        ('volunteer', '0005_auto_20191113_1107'),
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkmodel',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='organisation.Organisation', verbose_name='organisation'),
        ),
        migrations.AddField(
            model_name='bookmarkmodel',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='volunteer.Volunteer', verbose_name='volunteer'),
        ),
        migrations.AlterField(
            model_name='bookmarkmodel',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='call.Call', verbose_name='call'),
        ),
        migrations.AlterField(
            model_name='bookmarkmodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='event.Event', verbose_name='event'),
        ),
    ]
