# Generated by Django 2.2.6 on 2019-11-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0002_auto_20191106_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(blank=True, max_length=150, verbose_name='social')),
                ('languages', models.CharField(blank=True, max_length=150, verbose_name='languages')),
                ('sports', models.CharField(blank=True, max_length=150, verbose_name='sports')),
                ('arts_culture', models.CharField(blank=True, max_length=150, null=True, verbose_name='arts & culture')),
                ('coaching', models.CharField(blank=True, max_length=150, null=True, verbose_name='coaching')),
                ('food', models.CharField(blank=True, max_length=150, verbose_name='food')),
                ('politics', models.CharField(blank=True, max_length=150, verbose_name='politics')),
                ('items', models.CharField(blank=True, max_length=150, verbose_name='items')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='volunteer.Volunteer', verbose_name='volunteer')),
            ],
        ),
    ]
