# Generated by Django 2.2.6 on 2019-11-11 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='focus', to='organisation.Organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='focus',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='volunteer.Volunteer', verbose_name='volunteer'),
        ),
    ]
