# Generated by Django 2.2.6 on 2019-11-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_auto_20191111_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='arts_culture',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='arts & culture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='focus',
            name='coaching',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='coaching'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='focus',
            name='organisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus', to='organisation.Organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='focus',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='volunteer.Volunteer', verbose_name='volunteer'),
        ),
    ]
