export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
// export const LOGOUT = 'LOGOUT'
// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const GET_VOLUNTEER_PROFILE = 'GET_VOLUNTEER_PROFILE';
