export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const LOGGED_IN_USER = "LOGGED_IN_USER";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const GET_VOLUNTEER_BY_ID = "GET_VOLUNTEER_BY_ID";
export const GET_FEED_VOLUNTEER = "GET_FEED_VOLUNTEER";
