# Generated by Django 2.2.6 on 2019-11-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call', '0001_initial'),
        ('volunteer', '0002_auto_20191105_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('option_nr', models.IntegerField(verbose_name='option number')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_option', to='call.Call', verbose_name='call')),
                ('volunteer', models.ManyToManyField(related_name='call_option', to='volunteer.Volunteer', verbose_name='volunteer participating')),
            ],
        ),
    ]
