# Generated by Django 2.2.6 on 2019-11-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_option', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calloption',
            name='option_nr',
        ),
        migrations.AlterField(
            model_name='calloption',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_options', to='call.Call', verbose_name='call'),
        ),
        migrations.AlterField(
            model_name='calloption',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='call_options', to='volunteer.Volunteer', verbose_name='volunteer participating'),
        ),
    ]
