# Generated by Django 2.2.6 on 2019-11-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('controlled', 'controlled'), ('secret', 'secret')], default='private', max_length=100, verbose_name='privacy_setting'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='media-files', verbose_name='image'),
        ),
    ]
