# Generated by Django 2.2.6 on 2019-11-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20191105_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='media-files/volunteer/images', verbose_name='image'),
        ),
    ]
