# Generated by Django 2.2.6 on 2019-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20191106_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(upload_to='media-files/volunteer/images', verbose_name='image'),
        ),
    ]
