# Generated by Django 2.2.6 on 2019-11-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20191111_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='social_media',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='social media'),
        ),
    ]
