# Generated by Django 2.2.6 on 2019-11-06 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0004_volunteerreuqest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolunteerReuqest',
            new_name='VolunteerRequest',
        ),
    ]
