# Generated by Django 2.2.6 on 2019-11-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20191113_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='social_media',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='linkedin',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='LinkedIn'),
        ),
    ]
