# Generated by Django 2.2.6 on 2019-11-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20191113_0921'),
        ('volunteer', '0005_auto_20191113_1107'),
    ]

    operations = [
    ]
