# Generated by Django 2.2.6 on 2019-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('Non-profit organisation', 'Non-profit organisation'), ('Project', 'Project')], default='Non-profit organisation', max_length=100, verbose_name='type')),
                ('privacy_setting', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('controlled', 'controlled'), ('secret', 'secret')], default='private', max_length=100, verbose_name='privacy_setting')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='media-files', verbose_name='image')),
                ('document', models.FileField(null=True, upload_to='media-files', verbose_name='document')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('location', models.CharField(default='location', max_length=200)),
                ('description', models.TextField(default='description', verbose_name='description')),
                ('website', models.CharField(default='website', max_length=200)),
                ('phone', models.CharField(default='phone', max_length=200)),
            ],
        ),
    ]
