# Generated by Django 2.2.6 on 2019-11-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='document',
            field=models.FileField(null=True, upload_to='media-files/organisation/file', verbose_name='document'),
        ),
    ]
