# Generated by Django 2.2.6 on 2019-11-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20191106_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='media-files/organisation/images', verbose_name='image'),
        ),
    ]
