# Generated by Django 2.2.6 on 2019-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20191106_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media-files/organisation/file', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media-files/organisation/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
