# Generated by Django 2.2.6 on 2019-11-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20191106_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='terms_of_services',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
