# Generated by Django 2.2.6 on 2019-11-06 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0005_organisation_terms_of_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private'), ('controlled', 'controlled'), ('secret', 'secret')], default='private', max_length=100, verbose_name='Privacy setting'),
        ),
    ]
