# Generated by Django 2.2.6 on 2019-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20191106_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
