# Generated by Django 2.2.6 on 2019-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_auto_20191106_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media-files/organisation/images', verbose_name='image'),
        ),
    ]
