# Generated by Django 2.2.6 on 2019-11-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20191106_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['created']},
        ),
    ]
